### PR TITLE
fix dev issues

### LINKED ISSUE #840: Tcy balance bug
## Description

Not reading the balances properly

### PR DESCRIPTION
**Pull request by Thorian1te**
## Summary by CodeRabbit

* **New Features**
  * Enhanced swap interface to support both Thorchain and Mayachain pool data, enabling richer multi-chain swaps and improved asset handling.
  * Added localized messages in multiple languages to notify users when Midgard is offline for a given protocol.
  * Improved halted chain warnings to include Midgard's online/offline status for clearer alerts.
  * Added Midgard health status monitoring in provider modal and swap components for better protocol status awareness.

* **Bug Fixes**
  * The Ledger address input in wallet settings is now correctly disabled for EVM chains unless the appropriate HD mode is set.
  * Wallet account display for Ledger addresses is now consistently shown regardless of EVM HD mode.
  * Fixed minor UI typo in protocol list alignment.

* **Improvements**
  * Automatically switches to Ledger wallet for TCY tokens if only the Ledger wallet holds TCY.
  * Enhanced error handling and messaging for missing or unsupported swap assets.
  * Expanded external URL whitelist to include Mayachain-related hostnames for improved link handling.

### CODE REVIEW

File: src/renderer/components/modal/provider/ProviderModalContent.tsx [hunk 1]
```diff
@@ -32,6 +33,17 @@ export const ProviderModalContent = (props: Props) => {
     onClose()
   }, [onClose])
 
+  // Programmatically toggle protocols off if API is offline or failed
+  useEffect(() => {
+    if (RD.isFailure(midgardStatusRD)) {
+      setAggProtocol('Thorchain', false)
+    }
+    if (RD.isFailure(midgardStatusMayaRD)) {
+      console.log(RD.isFailure(midgardStatusMayaRD))
```
Comment (cinnamoroll6130) [inline src/renderer/components/modal/provider/ProviderModalContent.tsx]: This console log is intended?

**Review by cinnamoroll6130 — DISMISSED** [review]
lgtm

**Review by cinnamoroll6130 — APPROVED** [review]
lgtm
