### PR TITLE
fixed bsc and avax ledger & bumped bitcoin fees

### LINKED ISSUE #117: ADD: AVAX & BSC ledger Deposit
Configure AVAX & BSC chains for ledger deposit

### PR DESCRIPTION
**Pull request by Thorian1te**

### CODE REVIEW

File: src/renderer/services/bitcoin/common.ts [hunk 1]
```diff
@@ -30,7 +30,7 @@ const testnetHaskoinProvider = new HaskoinProvider(
 )
 
 const LOWER_FEE_BOUND = 1
-const UPPER_FEE_BOUND = 900
+const UPPER_FEE_BOUND = 2000
```
Comment (GrassRootsCrypto) [inline src/renderer/services/bitcoin/common.ts:34]: Why not make this double `UPPER_FEE_BOUND` in `xchainjs/xchain-bitcoin`?

Comment (Thorian1te) [reply src/renderer/services/bitcoin/common.ts:34]: not necessary

**Review by GrassRootsCrypto — APPROVED** [review]
