### PR TITLE
Fix withdraw Lp & may tx route

### LINKED ISSUE #147: Withdraw - lp
invalid - recipient address - rune ?

### PR DESCRIPTION
**Pull request by Thorian1te**

### CODE REVIEW

File: src/renderer/components/AssetsFilter/AssetsFilter.tsx [hunk 1]
```diff
@@ -27,7 +27,7 @@ export const AssetsFilter: React.FC<Props> = ({ poolFilters, className, activeFi
       __base__: intl.formatMessage({ id: 'common.asset.base' }),
       __usd__: 'usd',
       __erc20__: 'erc20',
-      __bep2__: 'bep2',
+      __avax__: 'avax',
```
Comment (GrassRootsCrypto) [inline src/renderer/components/AssetsFilter/AssetsFilter.tsx:30]: I did this too but this filter would only show usd as there are only two avax assets listed.

Comment (Thorian1te) [reply src/renderer/components/AssetsFilter/AssetsFilter.tsx:30]: thats okay

**Review by GrassRootsCrypto — APPROVED** [review]
