### PR TITLE
fix duplicate savers & update packages

### LINKED ISSUE #40: Display Savers From a Ledger
Savers with Ledger

Hello,

the savers of my ledger are not being displayed, even if I click on the Ledger box.
Also in my wallet it is not being displayed. In both cases I clicked on refresh

Screenshot 2023-09-11 102648
Screenshot 2023-09-11 102746

Windows 11 latest Asgardex app 1.20.4

regards

### LINKED ISSUE #67: Track transactions
Remove track Tx extra modal content for non swap transactions

Use 9 R track transactions for swaps only.

### LINKED ISSUE #68: Savers page not showing ledger savers
Savers only shows keystore savers, not ledger-based savers. 

If you go to wallet-> ledger -> earn then the correct savers info is there.

### LINKED ISSUE #69: Savers Withdraw Outbound time not displayed
Requires xchainjs fix

### LINKED ISSUE #76: Update xhcainjs clients
Update xhcainjs clients to the latest and test

### LINKED ISSUE #78: Change Block Interveral Range
Change form 1 to 10 to 1-3.

The default is 2.

### LINKED ISSUE #79: 1.20.6 Pool "LP Share" listed multiple times
## Prerequisites

I suspect you need to have a wallet with an LP position that has been added to a couple of times.

## Expected Behavior

LP for any pool should only be listed once.

## Current Behavior

I have a couple of LPs that I have added to numerous times. Under "LP Shares" each of those are listed more than once. For the one pool I have only done one deposit into, the LP position is only listed once. For each poll that is duplicated, each line it is listed on is identical.

## Steps to Reproduce

1. Have a wallet with an LP postion that has been added to at least ones (not counting the original)/
2. Go to "LP Shares" page
3. Notice duplicate entries and that the total balance is wrong.
4.

## Your Environment - Release Version (skip if not using a release version)

1.20.6 release on Debian Linux
- ASGARDEX desktop version: 1.20.6

- Operating system and version: Debian LInux Testing

### LINKED ISSUE #84: Refresh Overhaul
1) refresh is really needed, on every page. It should be on the header pane and allow to refresh page content (typically the balance). 
refresh everything
Wallet Home: refresh individual chains
Wallet/Asset: refresh balance
Wallet/Asset/SEND or DEPOSIT: refresh balance

### PR DESCRIPTION
**Pull request by Thorian1te**

### CODE REVIEW

File: src/renderer/helpers/walletHelper.ts [hunk 1]
```diff
@@ -130,6 +130,9 @@ export const getBnbAmountFromBalances = (balances: WalletBalances): O.Option<Ass
 export const getEthAmountFromBalances = (balances: WalletBalances): O.Option<AssetAmount> =>
   getAssetAmountFromBalances(balances, isEthAsset)
 
+export const getEVMAmountFromBalances = (balances: WalletBalances): O.Option<AssetAmount> =>
```
Comment (GrassRootsCrypto) [inline src/renderer/helpers/walletHelper.ts:133]: This should replace getBscAmountFromBalances, getAvaxAmountFromBalances and getEthAmountFromBalances. so can they be deleted?

File: src/renderer/components/swap/Swap.tsx [hunk 2]
```diff
@@ -1407,22 +1407,28 @@ export const Swap = ({
...
+    setStreamingInterval(1) // Default position
     setStreamingQuantity(0) // thornode decides the swap quantity
-    setSlider(30)
+    setSlider(26)
     setIsStreaming(true)
   }
 
   // Streaming Interval slider
   const renderStreamerInterval = useMemo(() => {
+    const calculateStreamingInterval = (slider: number) => {
```
Comment (GrassRootsCrypto) [inline src/renderer/components/swap/Swap.tsx:1418]: I preferred the prev version. Forcing the range into position is better than what the pic has. 
image

File: src/renderer/helpers/walletHelper.ts (hunk 1 above)
Comment (Thorian1te) [reply src/renderer/helpers/walletHelper.ts:130]: maybe, id like to leave them there for now

**Review by GrassRootsCrypto — APPROVED** [review]
